DROP TABLE IF EXISTS `sys_user`;

CREATE TABLE `sys_user` (
	`id` BIGINT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	`user_name` VARCHAR(255) NOT NULL UNIQUE,
	`nick_name` VARCHAR(255) NOT NULL,
	`password` VARCHAR(255) NOT NULL,
	`salt` VARCHAR(255) NOT NULL,
	`email` VARCHAR(128) DEFAULT NULL,
	`phone` VARCHAR(32) DEFAULT NULL,
	`head` VARCHAR(1024) DEFAULT NULL,
	`sex` TINYINT NOT NULL DEFAULT 1,
	`tenant_id` BIGINT DEFAULT NULL,
	`gmt_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`gmt_modify` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `sys_role`;

CREATE TABLE `sys_role`(
	`id` BIGINT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	`name` VARCHAR(1024) NOT NULL,
	`identifier` VARCHAR(64) NOT NULL,
	`description` VARCHAR(1024) NULL
);

DROP TABLE IF EXISTS `sys_user_role`;

CREATE TABLE `sys_user_role`(
	`id` BIGINT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	`user_id` BIGINT NOT NULL,
	`role_id` BIGINT NOT NULL
);


DROP TABLE IF EXISTS `sys_permission`;

CREATE TABLE `sys_permission`(
	`id` BIGINT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	`name` VARCHAR(64) NOT NULL,
	`identifier` VARCHAR(64) NOT NULL,
	`description` VARCHAR(1024) NULL
);

DROP TABLE IF EXISTS `sys_role_permission`;

CREATE TABLE `sys_role_permission`(
	`id` BIGINT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	`role_id` BIGINT NOT NULL,
	`permission_id` BIGINT NOT NULL
);

DROP TABLE IF EXISTS `sys_api_permission`;

CREATE TABLE `sys_api_permission`(
	`id` BIGINT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	`api` VARCHAR(1024) NOT NULL,
	`method` ENUM('GET','PUT','POST','DELETE','PATCH') NOT NULL DEFAULT 'GET',
	`permission` VARCHAR(1024) NOT NULL
);