DROP TABLE IF EXISTS `sys_user`;

CREATE TABLE `sys_user` (
	`id` BIGINT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	`user_name` VARCHAR(255) NOT NULL UNIQUE,
	`nick_name` VARCHAR(255) NOT NULL,
	`password` VARCHAR(255) NOT NULL,
	`salt` VARCHAR(255) NOT NULL,
	`email` VARCHAR(128) DEFAULT NULL,
	`phone` VARCHAR(32) DEFAULT NULL,
	`head` VARCHAR(1024) DEFAULT NULL,
	`sex` TINYINT NOT NULL DEFAULT 1,
	`tenant_id` BIGINT DEFAULT NULL,
	`gmt_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`gmt_modify` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);